/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as R404RouteImport } from './404'
import { Route as IndexRouteImport } from './index'
import { Route as ServicesSpaRouteImport } from './services/spa'
import { Route as ServicesHairRouteImport } from './services/hair'
import { Route as ServicesColorRouteImport } from './services/color'
import { Route as ServicesBridalRouteImport } from './services/bridal'
import { Route as ServicesLayoutRouteImport } from './services/_layout'
import { Route as BookingConfirmationRouteImport } from './booking/confirmation'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSpaRoute = ServicesSpaRouteImport.update({
  id: '/services/spa',
  path: '/services/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHairRoute = ServicesHairRouteImport.update({
  id: '/services/hair',
  path: '/services/hair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesColorRoute = ServicesColorRouteImport.update({
  id: '/services/color',
  path: '/services/color',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBridalRoute = ServicesBridalRouteImport.update({
  id: '/services/bridal',
  path: '/services/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLayoutRoute = ServicesLayoutRouteImport.update({
  id: '/services/_layout',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/services': typeof ServicesLayoutRoute
  '/services/bridal': typeof ServicesBridalRoute
  '/services/color': typeof ServicesColorRoute
  '/services/hair': typeof ServicesHairRoute
  '/services/spa': typeof ServicesSpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/services': typeof ServicesLayoutRoute
  '/services/bridal': typeof ServicesBridalRoute
  '/services/color': typeof ServicesColorRoute
  '/services/hair': typeof ServicesHairRoute
  '/services/spa': typeof ServicesSpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/services/_layout': typeof ServicesLayoutRoute
  '/services/bridal': typeof ServicesBridalRoute
  '/services/color': typeof ServicesColorRoute
  '/services/hair': typeof ServicesHairRoute
  '/services/spa': typeof ServicesSpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/booking/confirmation'
    | '/services'
    | '/services/bridal'
    | '/services/color'
    | '/services/hair'
    | '/services/spa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/booking/confirmation'
    | '/services'
    | '/services/bridal'
    | '/services/color'
    | '/services/hair'
    | '/services/spa'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/booking/confirmation'
    | '/services/_layout'
    | '/services/bridal'
    | '/services/color'
    | '/services/hair'
    | '/services/spa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  ServicesLayoutRoute: typeof ServicesLayoutRoute
  ServicesBridalRoute: typeof ServicesBridalRoute
  ServicesColorRoute: typeof ServicesColorRoute
  ServicesHairRoute: typeof ServicesHairRoute
  ServicesSpaRoute: typeof ServicesSpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/spa': {
      id: '/services/spa'
      path: '/services/spa'
      fullPath: '/services/spa'
      preLoaderRoute: typeof ServicesSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hair': {
      id: '/services/hair'
      path: '/services/hair'
      fullPath: '/services/hair'
      preLoaderRoute: typeof ServicesHairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/color': {
      id: '/services/color'
      path: '/services/color'
      fullPath: '/services/color'
      preLoaderRoute: typeof ServicesColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bridal': {
      id: '/services/bridal'
      path: '/services/bridal'
      fullPath: '/services/bridal'
      preLoaderRoute: typeof ServicesBridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/_layout': {
      id: '/services/_layout'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BookingConfirmationRoute: BookingConfirmationRoute,
  ServicesLayoutRoute: ServicesLayoutRoute,
  ServicesBridalRoute: ServicesBridalRoute,
  ServicesColorRoute: ServicesColorRoute,
  ServicesHairRoute: ServicesHairRoute,
  ServicesSpaRoute: ServicesSpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
